export function SeoContent() {
  // Natural language examples
  const naturalExamples = [
    "next Wednesday at 10am PST",
    "Friday 3pm EST",
    "tomorrow at noon GMT",
    "March 15th, 9:30am CET",
  ];
  
  // Technical format examples (ISO and Unix)
  const technicalExamples = [
    "2025-03-07T15:00-05:00",
    "1709830800",
  ];

  return (
    <section aria-labelledby="understanding-time" className="mb-16">
      <h2 
        id="understanding-time" 
        className="font-display text-[28px] mb-5"
        style={{
          color: '#1a1a1a',
          borderLeft: '3px solid #c8922a',
          paddingLeft: '16px',
        }}
      >
        Understanding ambiguous time references
      </h2>
      
      <div className="space-y-4 leading-relaxed font-sans text-[#4a4540]">
        <p>
          Time references in written communication are often unclear. When someone writes 
          &quot;3pm EST&quot; in an email, it may not account for daylight saving time. A message 
          saying &quot;next Wednesday&quot; depends entirely on when it was sent. Timestamps like 
          &quot;2025-03-07T15:00-05:00&quot; are precise but difficult to read at a glance.
        </p>
        
        <p>
          These ambiguities cause missed meetings, scheduling errors, and confusion across 
          time zones. The problem is especially common in emails, chat messages, calendar 
          invites, and system logs where time expressions are written by humans or 
          generated by different software systems.
        </p>
        
        <p>
          TimeMeaning interprets time references by identifying the timezone, checking 
          whether daylight saving time applies, resolving relative expressions like 
          &quot;next Friday,&quot; and presenting the result in a clear, unambiguous format with 
          the canonical ISO 8601 timestamp.
        </p>
      </div>

      {/* Example queries as interactive chips */}
      <aside className="mt-8">
        <h3 
          className="font-mono text-[11px] uppercase tracking-wider mb-4"
          style={{ color: '#c8922a', letterSpacing: '0.1em' }}
        >
          Example queries this tool can interpret
        </h3>
        <div className="flex flex-wrap gap-2">
          {/* Natural language chips - dark terminal style */}
          {naturalExamples.map((example, i) => (
            <span 
              key={i}
              className="font-mono text-[13px] cursor-pointer transition-colors"
              style={{
                background: '#1a1a1a',
                color: '#f5f0e8',
                padding: '6px 12px',
                borderRadius: '20px',
                border: '1px solid #3a3530',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.borderColor = '#c8922a';
                e.currentTarget.style.color = '#c8922a';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.borderColor = '#3a3530';
                e.currentTarget.style.color = '#f5f0e8';
              }}
            >
              {example}
            </span>
          ))}
          {/* Technical format chips */}
          {technicalExamples.map((example, i) => (
            <span 
              key={`tech-${i}`}
              className="font-mono text-[13px] cursor-pointer transition-colors"
              style={{
                background: '#1a1a1a',
                color: '#f5f0e8',
                padding: '6px 12px',
                borderRadius: '20px',
                border: '1px solid #3a3530',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.borderColor = '#c8922a';
                e.currentTarget.style.color = '#c8922a';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.borderColor = '#3a3530';
                e.currentTarget.style.color = '#f5f0e8';
              }}
            >
              {example}
            </span>
          ))}
        </div>
        
        {/* Easter Egg hint */}
        <p className="mt-6 text-[10px]" style={{ color: 'rgba(74,69,64,0.5)' }}>
          The tool also understands some things that aren&apos;t strictly times.
        </p>
        
        {/* Hall of Confusion link */}
        <p className="mt-4 text-sm">
          <a href="/hall-of-confusion" className="hover:underline" style={{ color: '#c8922a' }}>
            → See the Hall of Confusion
          </a>
        </p>
      </aside>

      {/* Section divider */}
      <hr className="mt-12 mb-12" style={{ borderTop: '1px solid #e0dbd4' }} />
    </section>
  );
}
